bookers2-debug-master/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end
  
  get '/search' => 'search#search'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'

end

bookers2-debug-master/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

bookers2-debug-master/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!
 
  def create
    @book = Book.find(params[:book_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.book_id = @book.id
    @post_comment.user_id = current_user.id
    @post_comment.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    post_comment = @book.post_comments.find(params[:id])
    post_comment.destroy
  end
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

bookers2-debug-master/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2-debug-master/app/views/post_comments/_comment_index.html.erb
<% book.post_comments.each do |post_comment| %>
  <% post_comment_user = post_comment.user %>
  <tr>
    <td>
      <%= link_to user_path(post_comment_user), class: "user_#{post_comment_user.id}" do %>
        <%= attachment_image_tag(post_comment_user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
        <%= post_comment_user.name %>
       <% end %>
    </td>
    <td>
      <%= post_comment.comment %>
    </td>
    <% if current_user == post_comment_user %>
    <td>
      <%= link_to "Destroy", book_post_comment_path(post_comment.book_id, post_comment.id), class: "btn btn-sm btn-danger", method: :delete, remote: true %>
    </td>
    <% end %>
  </tr>
<% end %>

bookers2-debug-master/app/views/post_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.post_comments.count %>");
$(".post_comments").html("<%= j(render 'post_comments/comment_index', book: @book) %>");
$("#post_comment_comment").val("");

bookers2-debug-master/app/views/post_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.post_comments.count %>");
$(".post_comments").html("<%= j(render 'post_comments/comment_index', book: @book) %>");
$("#post_comment_comment").val("");